### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by pasindu20** [MenuDocs/erela.js#187]
Update the erela.js npm package why its updated on here ?

**Comment by AlphaLupine** [comment]
Because I dont believe this repo will be updated by MenuDocs as it allows users to break Discord's terms of service

**Comment by pasindu20** [comment]
> Because I dont believe this repo will be updated by MenuDocs as it allows users to break Discord's terms of service

So it only update github version ?

**Comment by AlphaLupine** [comment]
The development team from MenuDocs is no longer maintaining this repo. 2D might come in every few months and make a change but thats about it.

**Comment by Anish-Shobith** [comment]
> Update the erela.js npm package why its updated on here ?

1. I don't find interest or motivation anymore towards discord API.
2. Due to recent change of discord not accepting music bots, I don't see the reason updating it anymore although this point still goes on with point 1 as saying "I have no interest at the moment"
3. The answer to your question: We the contributors don't have access to the pushing the changes to the npm.

I am not sure what are 2D's thoughts about this, but that's pretty much from me.

**Comment by Auxtal** [comment]
2D currently does not have access to his GitHub account or Discord account (And more). Just thought I'd let you know :)

**Comment by melike2d** [comment]
The npm package has been updated 👍🏼
