### ISSUE TITLE
"Plugin at index [x] does not extend Plugin." when loading Spotify plugin

### ISSUE THREAD

**Issue by NorteX-dev** [MenuDocs/erela.js#77]
When loading the Spotify Erela addon (https://github.com/Solaris9/erela.js-spotify), erela.js crashes with the message in the title. After further code inspection, I found out the Spotify plugin constructor does in fact extend it (https://github.com/Solaris9/erela.js-spotify/blob/master/src/plugin.ts#L66) but it isn't correctly recognized as one by the plugin loader.

To counter this and try to find a solution, when commenting out this line: https://github.com/Solaris9/erela.js/blob/master/src/structures/Manager.ts#L259 it obviously does not throw an error - as expected - but the manager does not finish loading and the `client.manager` property isn't populated.

This error may not be exclusive to the Spotify addon, it *could* also be affecting any other plugin, but I didn't check it.

Edit: code if needed
```js
client.manager = new Erela.Manager({
	nodes,
	plugins: [
		new Spotify({
			clientID: `something`
			clientSecret: `something`
		})
	],
	send(id, payload) {
		const guild = client.guilds.cache.get(id);
		if (guild) guild.shard.send(payload);
	},
})
```

**Comment by Solaris9** [comment]
This is because of transitive dependencies, if a dependency depends on package with a different version than what's in your package.json it will create a `node_modules` under the dependency, `instanceof` will not work with two different packages installed that try to use a class from it, it will reference the wrong one.

There is a temporary fix, using this [package](https://www.npmjs.com/package/npm-force-resolutions) to force npm to remove transitive dependencies based on what ones you specify, **if you use Yarn you will not need to install this, refer to the [documentation](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) for more.

A official fix would likely to make erela.js a development dependency so it will not install it along the others and use root `node_modules`, I will be fixing this soon.

**Comment by acollierr17** [comment]
@NorteX-dev Can you provide the following information relevant to your issue above? I just tried using the latest versions below and failed to reproduce the issue. 

- System OS/Distro Version
- Node.js Version
- Yarn and/or NPM versions
- Erela.js Version
- Erela.js-Spotify version
